name: DigitalOcean Droplet Manager

# This will show up in the Actions tab
# The actual name will be set in the job using environment variables

on:
  # Run automatically at 8:30 AM Vietnam time (GMT+7) every day
  schedule:
    - cron: '30 1 * * *'  # 8:30 AM Vietnam time
  
  # Allow manual trigger from GitHub UI
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        type: choice
        default: 'list'
        options:
        - create
        - delete
        - list
      droplet_id:
        description: 'Droplet ID (required for delete operation)'
        required: false
        type: string
      skip_delete:
        description: 'Skip deleting old proxies (only applies to scheduled runs)'
        required: false
        type: boolean
        default: false

jobs:
  manage-droplet:
    runs-on: ubuntu-latest
    # Set a custom name for the workflow run
    name: ${{ github.event_name == 'schedule' && 'Scheduled Run' || 'Manual Run' }} - ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.operation || 'create' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y jq curl

    # Scheduled run - Auto create proxy
    - name: Scheduled - Get existing droplets
      if: github.event_name == 'schedule'
      id: get_droplets
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        response=$(curl -s -X GET \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $DO_API_TOKEN" \
          "https://api.digitalocean.com/v2/droplets?tag_name=proxy")
        
        DROPLET_IDS=$(echo $response | jq -r '.droplets[].id' | tr '\n' ' ')
        
        if [ -n "$DROPLET_IDS" ]; then
          echo "droplet_ids=$DROPLET_IDS" >> $GITHUB_OUTPUT
          echo "Found droplets: $DROPLET_IDS"
        else
          echo "No existing proxy droplets found"
          echo "droplet_ids=" >> $GITHUB_OUTPUT
        fi

    - name: Scheduled - Delete old proxies
      if: github.event_name == 'schedule' && steps.get_droplets.outputs.droplet_ids != '' && !github.event.inputs.skip_delete
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        for id in ${{ steps.get_droplets.outputs.droplet_ids }}; do
          echo "Deleting droplet $id..."
          curl -X DELETE \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $DO_API_TOKEN" \
            "https://api.digitalocean.com/v2/droplets/$id"
          echo "Deleted droplet $id"
        done

    - name: Scheduled - Create new proxy
      if: github.event_name == 'schedule'
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        PROXY_USER: ${{ vars.PROXY_USER || 'proxyuser' }}
        PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD || 'proxypass123' }}
      run: |
        python create_proxy_singapore.py

    # Manual operations
    - name: Manual - List Droplets
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'list'
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        echo "Listing all proxy droplets..."
        curl -s -X GET \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $DO_API_TOKEN" \
          "https://api.digitalocean.com/v2/droplets?tag_name=proxy" | jq '.'

    - name: Manual - Create Droplet
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'create'
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        PROXY_USER: ${{ vars.PROXY_USER || 'proxyuser' }}
        PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD || 'proxypass123' }}
      run: |
        python create_proxy_singapore.py

    - name: Manual - Delete Droplet
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.operation == 'delete' && github.event.inputs.droplet_id != ''
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        echo "Deleting droplet ${{ github.event.inputs.droplet_id }}..."
        curl -X DELETE \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $DO_API_TOKEN" \
          "https://api.digitalocean.com/v2/droplets/${{ github.event.inputs.droplet_id }}"
        echo "Deleted droplet ${{ github.event.inputs.droplet_id }}"
